version: '3.1'
services: 
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - mongo-compose-network
    environment:
      MONGO_DB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_DB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: [--auth]
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - mongo-compose-network
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_ADDRESS}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_DB}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
    ports:
      - 8081:8081
    depends_on: 
      - mongo

  discord-translation-bot:
    working_dir: /App
    build: .
    networks:
      - mongo-compose-network
    restart: always
    environment:
      MONGO_ADDRESS: ${MONGO_ADDRESS}
      MONGO_DB: ${MONGO_DB}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    depends_on: 
      - mongo

networks:
  mongo-compose-network:
    driver: bridge